<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="com.acst.sign.SignUpTest" duration-ms="11231" started-at="2019-06-09T03:38:29Z" finished-at="2019-06-09T03:38:41Z">
    <groups>
      <group name="regression">
        <method signature="SignUpTest.newUserSignUpSuccessfull()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="newUserSignUpSuccessfull" class="com.acst.sign.SignUpTest"/>
        <method signature="SignUpTest.signUpAlreadySignUpedUser()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="signUpAlreadySignUpedUser" class="com.acst.sign.SignUpTest"/>
        <method signature="SignUpTest.signUpWithoutMandatoryParameter()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="signUpWithoutMandatoryParameter" class="com.acst.sign.SignUpTest"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="SignUpTest.newUserSignUpSuccessfull()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="newUserSignUpSuccessfull" class="com.acst.sign.SignUpTest"/>
        <method signature="SignUpTest.signUpAlreadySignUpedUser()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="signUpAlreadySignUpedUser" class="com.acst.sign.SignUpTest"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Command line test" duration-ms="11231" started-at="2019-06-09T03:38:29Z" finished-at="2019-06-09T03:38:41Z">
      <class name="com.acst.sign.SignUpTest">
        <test-method status="FAIL" signature="newUserSignUpSuccessfull()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="newUserSignUpSuccessfull" duration-ms="7786" started-at="2019-06-09T03:38:29Z" description="Sign up for new user and verify whether signUp is successfull or not" finished-at="2019-06-09T03:38:37Z">
          <exception class="javax.ws.rs.InternalServerErrorException">
            <full-stacktrace>
              <![CDATA[javax.ws.rs.InternalServerErrorException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.cxf.jaxrs.client.AbstractClient.convertToWebApplicationException(AbstractClient.java:466)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:311)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:717)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:676)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:222)
at com.sun.proxy.$Proxy14.doSignUp(Unknown Source)
at com.acst.sign.SignBaseClient.signUp(SignBaseClient.java:23)
at com.acst.sign.SignUpHelper.doSignUp(SignUpHelper.java:24)
at com.acst.sign.SignUpTest.newUserSignUpSuccessfull(SignUpTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- javax.ws.rs.InternalServerErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newUserSignUpSuccessfull -->
        <test-method status="FAIL" signature="signUpAlreadySignUpedUser()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="signUpAlreadySignUpedUser" duration-ms="2737" started-at="2019-06-09T03:38:37Z" description="Sign up for already signedup user and verify" finished-at="2019-06-09T03:38:40Z">
          <exception class="javax.ws.rs.InternalServerErrorException">
            <full-stacktrace>
              <![CDATA[javax.ws.rs.InternalServerErrorException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.cxf.jaxrs.client.AbstractClient.convertToWebApplicationException(AbstractClient.java:466)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:311)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:717)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:676)
at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:222)
at com.sun.proxy.$Proxy14.doSignUp(Unknown Source)
at com.acst.sign.SignBaseClient.signUp(SignBaseClient.java:23)
at com.acst.sign.SignUpHelper.doSignUp(SignUpHelper.java:24)
at com.acst.sign.SignUpTest.signUpAlreadySignUpedUser(SignUpTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- javax.ws.rs.InternalServerErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpAlreadySignUpedUser -->
        <test-method status="PASS" signature="signUpWithoutMandatoryParameter()[pri:0, instance:com.acst.sign.SignUpTest@17c68925]" name="signUpWithoutMandatoryParameter" duration-ms="650" started-at="2019-06-09T03:38:40Z" description="Sign up without mandatory parameter and verify" finished-at="2019-06-09T03:38:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpWithoutMandatoryParameter -->
      </class> <!-- com.acst.sign.SignUpTest -->
    </test> <!-- Command line test -->
  </suite> <!-- com.acst.sign.SignUpTest -->
</testng-results>
